# Test against the version of node.js
environment:
matrix:
# node.js
- nodejs_version: "6"

#Install Scripts. (runs after repo cloning)
install:
  #Get the largest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs _ version
  #install modules
  - npm install

  #Post-install test scripts.
  - test_script:
  # Output useful info debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

  # Don't actually build.
  - build: off
